#pragma once

enum TEXTYPE	{ TEX_SINGLE, TEX_MULTI, TEX_END };

enum  OBJID     {  OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_SHIELD, OBJ_UI, OBJ_END };

enum MAPID {STAGE01, STAGE02, STAGE03, STAGE04};
#pragma region е╦ют(enum class)

enum PCKTYPE
{
	PCK_NORMAL,
	PCK_FIRE,
	PCK_WATER,
	PCK_GRASS,
	PCK_ELECTRIC,
	PCK_ICE,
	PCK_FIGHT,
	PCK_POISON,
	PCK_GROUND,
	PCK_FLYING,
	PCK_PSYCHIC,
	PCK_BUG,
	PCK_ROCK,
	PCK_GHOST,
	PCK_DRAGON,
	PCK_DARK,
	PCK_STEEL,
	PCK_FAIRY,
	PCK_TYPE_END
};

#pragma endregion
